server:
  port: 8015

spring:

  application:
    name: authentication-api
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      javax:
        persistence:
          validation:
            mode: none
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  datasource:
    hikari:
      maximum-pool-size: 10
      connection-timeout: 10000
      minimum-idle: 2
      idle-timeout: 10000
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:Testdb01.}

secret.key: ${KEY:Test123}
