apiVersion: v1
kind: Service
metadata:
  name: mail-api
  labels:
    app: mail-api
spec:
  ports:
    - name: http
      port: 8015
      targetPort: 8015
      protocol: TCP
  selector:
    app: mail-api
  type: NodePort

